name: postgresql-prisma-pgadmin
services:
  postgres:
    image: postgres:15
    container_name: postgres-pokemon
    environment:
      POSTGRES_USER:     "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:       "${POSTGRES_DB}"
    volumes:
      - postgresql-prisma-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL:    "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_CONFIG_SERVER_MODE}"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-web-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-pokemon
    command:
      - redis-server
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  nextjs:
    image: my-nextjs-app:latest
    container_name: nextjs-pokemon
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - PORT=${NEXTJS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - CACHE_LOG_HITS=${CACHE_LOG_HITS}
    ports:
      - "${NEXTJS_PORT}:${NEXTJS_PORT}"
    restart: unless-stopped

volumes:
  postgresql-prisma-data:
  pgadmin-web-data:
  redis-data:

